# Generated by Django 3.0.2 on 2020-01-23 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('number', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('citizenship', models.CharField(max_length=64, null=True, verbose_name='国籍')),
                ('native_from', models.CharField(max_length=64, null=True, verbose_name='籍贯')),
                ('foreign_name', models.CharField(max_length=64, null=True, verbose_name='外语')),
                ('birthday', models.DateField(null=True, verbose_name='出生年月')),
                ('card_kind', models.CharField(max_length=32, verbose_name='证件类型')),
                ('ID_number', models.CharField(max_length=32, verbose_name='证件号')),
                ('politics', models.CharField(max_length=64, null=True, verbose_name='政治面貌')),
                ('section', models.CharField(max_length=64, null=True, verbose_name='乘车区间')),
                ('gender', models.CharField(max_length=32, verbose_name='性别')),
                ('nation', models.CharField(max_length=32, null=True, verbose_name='民族')),
                ('academy', models.CharField(max_length=64, verbose_name='学院')),
                ('major', models.CharField(max_length=64, verbose_name='专业')),
                ('class_number', models.CharField(max_length=32, verbose_name='学号')),
                ('category', models.CharField(max_length=32, verbose_name='班级')),
                ('province', models.CharField(max_length=32, null=True, verbose_name='高考考区')),
                ('score', models.FloatField(null=True, verbose_name='高考分数')),
                ('exam_number', models.CharField(max_length=32, null=True, verbose_name='高考证号')),
                ('graduate_from', models.CharField(max_length=64, null=True, verbose_name='毕业高中')),
                ('enroll_number', models.CharField(max_length=32, null=True, verbose_name='入学录取证号')),
                ('enroll_method', models.CharField(max_length=32, null=True, verbose_name='入学方式')),
                ('enroll_at', models.DateField(null=True, verbose_name='入学日期')),
                ('graduate_at', models.DateField(null=True, verbose_name='毕业日期')),
                ('foreign_language', models.CharField(max_length=32, null=True, verbose_name='外语语种')),
                ('train_method', models.CharField(max_length=32, null=True, verbose_name='培养方案')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='家庭住址')),
                ('zip', models.CharField(max_length=32, null=True, verbose_name='邮编')),
                ('phone', models.CharField(max_length=16, null=True, verbose_name='手机号')),
                ('email', models.CharField(max_length=64, null=True, verbose_name='邮箱')),
                ('roll_number', models.CharField(max_length=64, null=True, verbose_name='学籍表号')),
                ('source_from', models.CharField(max_length=255, null=True, verbose_name='学生来源')),
                ('graduate_to', models.CharField(max_length=255, null=True, verbose_name='毕业去向')),
                ('comment', models.CharField(max_length=255, null=True, verbose_name='备注')),
                ('img_url', models.URLField(verbose_name='头像地址')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'db_table': 'info',
                'ordering': ['-last_updated', '-number'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['-last_login', 'username'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=64, verbose_name='课程号')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='课程名')),
                ('course_number', models.IntegerField(null=True, verbose_name='选课序号')),
                ('scores', models.CharField(max_length=16, null=True, verbose_name='成绩')),
                ('credit', models.FloatField(null=True, verbose_name='学分')),
                ('inspect_method', models.CharField(max_length=64, null=True, verbose_name='考核方式')),
                ('course_properties', models.CharField(max_length=64, null=True, verbose_name='选课属性')),
                ('status', models.CharField(max_length=64, null=True, verbose_name='备注：正常，挂科')),
                ('exam_categories', models.CharField(max_length=64, null=True, verbose_name='考试类别')),
                ('semester', models.CharField(max_length=32, verbose_name='学年学期')),
                ('is_delay_exam', models.CharField(max_length=8, null=True, verbose_name='是否缓考')),
                ('details_print_id', models.CharField(max_length=128, null=True, verbose_name='打卷申请ID')),
                ('made_up_of', models.CharField(max_length=128, null=True, verbose_name='成绩组成')),
                ('daily_score', models.CharField(max_length=8, null=True, verbose_name='平时成绩')),
                ('midterm_score', models.CharField(max_length=8, null=True, verbose_name='期中成绩')),
                ('exam_score', models.CharField(max_length=8, null=True, verbose_name='考试成绩')),
                ('final_score', models.CharField(max_length=8, null=True, verbose_name='最终成绩')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('username',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='web.User')),
            ],
            options={
                'db_table': 'exam_score',
                'ordering': ['-semester', '-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='ExamPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='课程名')),
                ('room', models.CharField(max_length=32, verbose_name='考场')),
                ('date', models.DateField(verbose_name='考试日期')),
                ('time', models.CharField(max_length=32, verbose_name='考试时间')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_plan',
                                               to='web.User')),
            ],
            options={
                'db_table': 'exam_plan',
                'ordering': ['username', '-date'],
            },
        ),
        migrations.CreateModel(
            name='CET',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=16, verbose_name='考试日期')),
                ('level', models.CharField(max_length=16, verbose_name='等级')),
                ('score', models.CharField(max_length=16, null=True, verbose_name='分数')),
                ('username',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cet', to='web.User')),
            ],
            options={
                'db_table': 'cet',
                'ordering': ['username', '-date'],
            },
        ),
    ]
