# Generated by Django 3.0.2 on 2020-01-29 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0002_auto_20200128_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='status',
            field=models.CharField(max_length=64, null=True, verbose_name='备注：正常/挂科'),
        ),
        migrations.CreateModel(
            name='ClassCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=32, verbose_name='学年学期')),
                ('course_id', models.CharField(max_length=32, verbose_name='课程号')),
                ('course_number', models.IntegerField(null=True, verbose_name='选课序号')),
                ('course_name', models.CharField(max_length=64, verbose_name='课程名称')),
                ('teacher', models.CharField(max_length=32, verbose_name='任课教师')),
                ('credit', models.FloatField(null=True, verbose_name='学分')),
                ('course_properties', models.CharField(max_length=64, null=True, verbose_name='选课属性')),
                ('inspect_method', models.CharField(max_length=64, null=True, verbose_name='考核方式')),
                ('status', models.CharField(max_length=64, null=True, verbose_name='正常/挂科')),
                ('is_delay_exam', models.CharField(max_length=8, null=True, verbose_name='是否缓考')),
                ('details', models.CharField(max_length=64, null=True, verbose_name='上课时间、地点\t')),
                ('comment', models.TextField(null=True, verbose_name='备注')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.User')),
            ],
            options={
                'db_table': 'class_course',
                'ordering': ['username'],
            },
        ),
    ]
