# Generated by Django 3.0.2 on 2020-01-29 08:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0003_auto_20200129_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classcourse',
            options={'ordering': ['username', '-semester']},
        ),
    ]
