# Generated by Django 3.0.2 on 2020-01-29 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0004_auto_20200129_0831'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cet',
            table='lntu_cet',
        ),
        migrations.AlterModelTable(
            name='classcourse',
            table='lntu_class_course',
        ),
        migrations.AlterModelTable(
            name='examplan',
            table='lntu_exam_plan',
        ),
        migrations.AlterModelTable(
            name='score',
            table='lntu_exam_score',
        ),
        migrations.AlterModelTable(
            name='studentinfo',
            table='lntu_user_info',
        ),
        migrations.AlterModelTable(
            name='teachingplancourse',
            table='lntu_teaching_plan',
        ),
        migrations.AlterModelTable(
            name='user',
            table='lntu_user',
        ),
    ]
