# Generated by Django 3.0.2 on 2020-01-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0005_auto_20200129_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='教室')),
                ('capacity', models.IntegerField(default=-1, verbose_name='容量')),
                ('category', models.CharField(max_length=32, verbose_name='类别')),
                ('monday', models.CharField(max_length=32, verbose_name='周一')),
                ('tuesday', models.CharField(max_length=32, verbose_name='周二')),
                ('wednesday', models.CharField(max_length=32, verbose_name='周三')),
                ('thursday', models.CharField(max_length=32, verbose_name='周四')),
                ('friday', models.CharField(max_length=32, verbose_name='周五')),
                ('saturday', models.CharField(max_length=32, verbose_name='周六')),
                ('sunday', models.CharField(max_length=32, verbose_name='周日')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lntu_classroom',
                'ordering': ['name'],
            },
        ),
    ]
