# Generated by Django 3.0.2 on 2020-01-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0007_auto_20200130_0309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['buildingId', 'name']},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='buildingId',
            field=models.IntegerField(default=-1, verbose_name='教学楼编号'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
