# Generated by Django 3.0.2 on 2020-01-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0008_auto_20200130_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_id',
            field=models.CharField(max_length=32, null=True, verbose_name='最近学期的课程表ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(max_length=32, null=True, verbose_name='用于获取成绩的学生ID'),
        ),
    ]
