# Generated by Django 3.0.2 on 2020-02-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0012_auto_20200201_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'ordering': ['-last_updated', '-username']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-latest_login', 'username']},
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='number',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_login',
            new_name='latest_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='GPA',
        ),
        migrations.AddField(
            model_name='user',
            name='latest_GPA',
            field=models.FloatField(null=True, verbose_name='Grade Point Average'),
        ),
    ]
