# Generated by Django 3.0.2 on 2020-02-06 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='阳光体育ID')),
                ('number', models.CharField(max_length=32, null=True, verbose_name='学号')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='姓名')),
                ('gender', models.CharField(max_length=8, null=True, verbose_name='性别')),
                ('school', models.CharField(max_length=64, null=True, verbose_name='学校')),
                ('college', models.CharField(max_length=32, null=True, verbose_name='院系')),
                ('i_class', models.CharField(max_length=255, null=True, verbose_name='班级')),
                ('total_records', models.IntegerField(null=True)),
                ('morning_records', models.IntegerField(null=True)),
                ('success_records', models.IntegerField(null=True)),
                ('failure_records', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'aipao_user',
            },
        ),
        migrations.CreateModel(
            name='Success',
            fields=[
                ('IIDD', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('client_type', models.CharField(max_length=32, verbose_name='客户端类型')),
                ('speed', models.FloatField(null=True, verbose_name='配速')),
                ('step', models.IntegerField(null=True, verbose_name='步数')),
                ('cost_time_min', models.CharField(max_length=16, null=True, verbose_name='花费时间(min)')),
                ('cost_time_s', models.FloatField(null=True, verbose_name='花费时间(s)')),
                ('distance', models.FloatField(null=True, verbose_name='跑步距离')),
                ('standard_distance', models.FloatField(null=True, verbose_name='标准距离')),
                ('date', models.DateField(null=True, verbose_name='开始日期')),
                ('time', models.CharField(max_length=16, null=True, verbose_name='开始时刻')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aipao.Student')),
            ],
            options={
                'db_table': 'aipao_success',
            },
        ),
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('IIDD', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('client_type', models.CharField(max_length=32, verbose_name='客户端类型')),
                ('speed', models.FloatField(null=True, verbose_name='配速')),
                ('step', models.IntegerField(null=True, verbose_name='步数')),
                ('cost_time_min', models.CharField(max_length=16, null=True, verbose_name='花费时间(min)')),
                ('cost_time_s', models.FloatField(null=True, verbose_name='花费时间(s)')),
                ('distance', models.FloatField(null=True, verbose_name='跑步距离')),
                ('standard_distance', models.FloatField(null=True, verbose_name='标准距离')),
                ('date', models.DateField(null=True, verbose_name='开始日期')),
                ('time', models.CharField(max_length=16, null=True, verbose_name='开始时刻')),
                ('reason', models.CharField(max_length=32, verbose_name='失败原因')),
                ('reason_id', models.IntegerField(null=True, verbose_name='失败原因 ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aipao.Student')),
            ],
            options={
                'db_table': 'aipao_failure',
            },
        ),
    ]
